### ISSUE TITLE
XML generated for parse errors lacks identifier key

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/csslint#4]
Context: https://github.com/codeclimate/codeclimate-csslint/issues/25

To reproduce, create a gzip-compressed CSS file with `.gz.css` extension and run `codeclimate analyze` with this engine. Observe the resulting XML for this case (parse error) lacks our custom `identifier` key:

``` xml
<error line="1" column="1" severity="error" message="Unexpected token '"/>
```

**Comment by wfleming** [comment]
I think https://github.com/codeclimate/codeclimate-csslint/pull/34 would address this from the engine side: wouldn't stop getting errors, but would handle them better so analysis can continue on valid files.

**Comment by dblandin** [comment]
@pbrisbin Is this still an issue that we should track?

**Comment by pbrisbin** [comment]
I think with the patch linked to by @wfleming we can stop explicitly tracking this. If it comes up again someone can re-open a new Issue.
